// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhEDeNIHeYb1BcR9nS_H9EQnddJtNeI4',
    appId: '1:266512495961:web:4926c5784358fc52014848',
    messagingSenderId: '266512495961',
    projectId: 'todoapp-c8963',
    authDomain: 'todoapp-c8963.firebaseapp.com',
    storageBucket: 'todoapp-c8963.appspot.com',
    measurementId: 'G-M6LH7PCR74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQzW_4vw3C38nNi3L-NicOlL0xwow7z54',
    appId: '1:266512495961:android:4375047cd69b7cb3014848',
    messagingSenderId: '266512495961',
    projectId: 'todoapp-c8963',
    storageBucket: 'todoapp-c8963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDv6wNNEO0Tfjz8qc2npVxN_pdtoOLLPQ',
    appId: '1:266512495961:ios:b3896853cc5e8196014848',
    messagingSenderId: '266512495961',
    projectId: 'todoapp-c8963',
    storageBucket: 'todoapp-c8963.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDv6wNNEO0Tfjz8qc2npVxN_pdtoOLLPQ',
    appId: '1:266512495961:ios:a0ff78462ded438a014848',
    messagingSenderId: '266512495961',
    projectId: 'todoapp-c8963',
    storageBucket: 'todoapp-c8963.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
